name: Check Stock Availability

on:
  schedule:
    - cron: "*/5 6-8 * * *" # This covers both the 6-7 hour range and the first 30 minutes of hour 8
  workflow_dispatch:
    inputs:
      product-name:
        description: "Product name to check (e.g., ozempic, adiro)"
        required: false
        default: "ozempic"
        type: string

jobs:
  check-stock:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Create screenshots directory
        run: mkdir -p screenshots

      - name: Run stock checker
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PRODUCT_NAME: ${{ github.event.inputs.product-name }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ENABLE_TELEGRAM: "true"
        run: node check-stock.js
